#!/data/data/com.termux/files/usr/bin/bash
#
# Install mariadb
database="mariadb" || "mysql";

if ! [ command -v $database >/dev/null 2>&1 ]; then
	echo -e "\e[32;mPaket $database sudah terinstall.\e[0m";
else
	echo -e "\e[32;mPaket mysql belum terinstall.\e[0m";
fi
