#!/usr/bin/bash
#
# Installation Webserver
#
# @author Ayus Irfang Filaras <ayus.sahabat@gmail.com
# @lisence GPL
#
export WEB_SERVER_DIR=$(pwd)

# Memanggil web fungsi
if [ -f "${WEB_SERVER_DIR}/library/web_function" ]; then
	source "${WEB_SERVER_DIR}/library/web_function"
else
	echo -ne "\nError: File ${WEB_SERVER_DIR}/library/web_function tidak ada.\n"
	exit 1
fi

# Hanya untuk mengetest
# web_function_test

# Daftar paket instalasi web
DAFTAR_PAKET_WEB=($(cat daftar-paket.txt | tr '\n' ' '));

# Mengatur penyimpanan
termux-setup-storage

# Menjalankan program
INSTALL_WEB_SERVER
