#!/usr/bin/bash
#
# Install mariadb
#
PAKET_DATABASE="mariadb" || "mysql";

checkDB()
{
    # Cek paket database jija sudah ada
    progress "Cek paket database" 3

    if ! [ command -v $PAKET_DATABASE >/dev/null 2>&1 ]; then
        echo -e "\e[32;mPaket $PAKET_DATABASE sudah terinstall.\e[0m";
    else
        echo -e "\e[32;mPaket $PAKET_DATABASE belum terinstall.\e[0m";
        # Install paket database
        apt install mariadb -y
    fi
}

progress()
{
    echo -ne "\n\e[33;m${1}\e[0m ";
    timeout=0;

    echo -ne "\e[34;m";

    while [ $timeout -lt ${2} ]
    do
        timeout=`expr $timeout + 1`
        echo -ne "${timeout}" | sed 's/[0-9]/./g';
        sleep 1
    done
    echo -ne "\e[0m\n\n";
 }
