#!/usr/bin/bash
#
# Update termux webserver
#
# Alamat untuk pengunduhan file dari server
lib="https://raw.githubusercontent.com/apolbox/termux-webserver/dev"

# Daftar file yang akan diunduh dari server
list=(
    library/autoload 
    library/functions/core 
    library/functions/lampp_updater 
    library/functions/pma_installer 
    library/functions/repository 
    library/functions/settings
    library/functions/download
)

rm -rf library/*

# Pengolahan unduhan dan pengecekan file local
# dengan file yang berada diserver.
for i in ${!list[@]}
do
    if ! [ -d "library/functions" ]; then
        mkdir library/functions
    fi
    
    echo -e "\e[32;m[+] Mengunduh ${list[$i]} $(curl -# ${lib}/${list[$i]} --output ${list[$i]})\e[0m"
done

# Download repository
$(curl -s https://raw.githubusercontent.com/apolbox/termux-webserver/dev/repository.zip > repository.zip)
if ! [ -d "repository" ]; then
    mkdir -p repository
    unzip repository.zip -d ./repository
    clear
else
    unzip -f repository.zip -d ./repository
    clear
fi

# Memuat library untuk melakukan pengecekan pembaruan
# dari versi termux webserver yang terinstall dan
# termux yang telah rilis terbaru dari server.
source library/autoload

SLEEP_DURATION=.01
export SLEEP_DURATION

# Cek pembaruan repository
# Lakukan pembaruan repository lokal dengan repository dari server
# yang telah rilis terbaru
#URL_DOWNLOAD="https://api.github.com/repos/apolbox/termux-webserver/git/trees/b79dd00545b086adef5fefd4bb601cc21850ca32"
#URL_DOWNLOAD="https://codeload.github.com/apolbox/termux-webserver/legacy.zip/v1.1"

URL_DOWNLOAD="repos/wadahkode/termux-webserver/zipball/"
export URL_DOWNLOAD

repository --update

# Cek phpMyAdmin
pmaCheckInstallation true
