#!/usr/bin/bash
#
# @license Apache-2.0
option="${1}";
fileConfig=/data/data/com.termux/files/usr/var/etc/config/lighttpd.conf
host=127.0.0.1
port=8080

case ${option} in
    "start")
        lighttpd -f $fileConfig
        echo -e "\e[32;mWebserver berjalan di http://$host:$port/\n\e[0m"
        ;;

    "stop")
        echo -e "\e[32;mMenghentikan webserver yang berjalan di http://$host:$port/\e[0m\n";
        killall lighttpd
        ;;
    
    "--help")
        echo -e "usage: `basename ${0}` [start|stop] [-v version] [--help help]\n"
        ;; 

    #"--edit-config")
    #    echo "${2}" > tmp/edit-config.txt | sed -i 's=/=\\/=g' tmp/edit-config.txt;
    #    x=$(cat tmp/edit-config.txt | awk '{print $1}')
	#    y=$(cat ${fileConfig} | tr '\n' '\r' | awk '{print $1}')
	#    echo "server.document-root=" | sed -i "s|${y}|\"${x}\"|g" ${fileConfig}
    #
    #   echo -e "\e[32;m[√] File konfigurasi berhasil diperbarui.\e[0m"
    #   ;;

    "-v")
	    echo -e "\e[32;mLampp version \e[31;m1.0\e[0m\e[0m";;

    *)
	    echo "usage: `basename ${0}` [start|stop] [-v version] [--help help]\n" 
	    exit 1 # Command to come out of the program with status 1;;
esac
